### ISSUE TITLE
code is not working 

### ISSUE THREAD

**Issue by rajashekarc111** [farizrifqi/Threads-Media-Downloader#1]
getting An error occurred while fetching the media. Please try again later please fix ASAP

**Comment by farizrifqi** [comment]
what kind of error?

maybe u can send image or smth

**Comment by rajashekarc111** [comment]
now it is showing too many usage for today. try again later

**Comment by rajashekarc111** [comment]
hi i have sent message on telegram can you check

**Comment by farizrifqi** [comment]
issue will be closed in 12hrs if there's no any problem 🤗
