### ISSUE TITLE
Convert Videos to GIF

### ISSUE THREAD

**Issue by Suleman-Elahi** [farizrifqi/Threads-Media-Downloader#3]
Some posts have GIF instead of Videos. It i only downloads them as videos. But GIF needs to be GIF as well so consider adding an option to get GIF in output if possible.

**Comment by farizrifqi** [comment]
Can you provide me with example of the post URL? I thought nobody cares about GIFs.

**Comment by Suleman-Elahi** [comment]
https://www.threads.net/@_hewhoremains/post/CyiD5FVPs2r

**Comment by farizrifqi** [comment]
Thank you, I will update the code soon.

**Comment by farizrifqi** [comment]
I've just check the response from URL above, GIFs are formatted as MP4 as well. There's no differences between GIF and Video on the response. So, if about to result the actual gif, then I should put mp4-gif converting code. But I think it not too suitable to put it on this code.

**Comment by Suleman-Elahi** [comment]
Ok.
